//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Detection) DeepCopyInto(out *Detection) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Detection.
func (in *Detection) DeepCopy() *Detection {
	if in == nil {
		return nil
	}
	out := new(Detection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilesystemObservation) DeepCopyInto(out *FilesystemObservation) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilesystemObservation.
func (in *FilesystemObservation) DeepCopy() *FilesystemObservation {
	if in == nil {
		return nil
	}
	out := new(FilesystemObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReference) DeepCopyInto(out *ResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReference.
func (in *ResourceReference) DeepCopy() *ResourceReference {
	if in == nil {
		return nil
	}
	out := new(ResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceMountObservation) DeepCopyInto(out *SourceMountObservation) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceMountObservation.
func (in *SourceMountObservation) DeepCopy() *SourceMountObservation {
	if in == nil {
		return nil
	}
	out := new(SourceMountObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeRemediation) DeepCopyInto(out *VolumeRemediation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeRemediation.
func (in *VolumeRemediation) DeepCopy() *VolumeRemediation {
	if in == nil {
		return nil
	}
	out := new(VolumeRemediation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolumeRemediation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeRemediationList) DeepCopyInto(out *VolumeRemediationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VolumeRemediation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeRemediationList.
func (in *VolumeRemediationList) DeepCopy() *VolumeRemediationList {
	if in == nil {
		return nil
	}
	out := new(VolumeRemediationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VolumeRemediationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeRemediationSpec) DeepCopyInto(out *VolumeRemediationSpec) {
	*out = *in
	out.PVCRef = in.PVCRef
	out.PVRef = in.PVRef
	in.Detection.DeepCopyInto(&out.Detection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeRemediationSpec.
func (in *VolumeRemediationSpec) DeepCopy() *VolumeRemediationSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeRemediationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeRemediationStatus) DeepCopyInto(out *VolumeRemediationStatus) {
	*out = *in
	if in.QuiesceStartedAt != nil {
		in, out := &in.QuiesceStartedAt, &out.QuiesceStartedAt
		*out = (*in).DeepCopy()
	}
	if in.RestageStartedAt != nil {
		in, out := &in.RestageStartedAt, &out.RestageStartedAt
		*out = (*in).DeepCopy()
	}
	if in.Filesystem != nil {
		in, out := &in.Filesystem, &out.Filesystem
		*out = new(FilesystemObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.SourceMount != nil {
		in, out := &in.SourceMount, &out.SourceMount
		*out = new(SourceMountObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeRemediationStatus.
func (in *VolumeRemediationStatus) DeepCopy() *VolumeRemediationStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeRemediationStatus)
	in.DeepCopyInto(out)
	return out
}
