apiVersion: apps/v1
kind: Deployment
metadata:
  name: volumediator-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "volumediator.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: volumediator
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: volumediator
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: volumediator-controller
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - controller
            - --webhook-namespace=$(POD_NAMESPACE)
            - --force-delete-after={{ .Values.controller.forceDeleteAfter }}
            - --unstage-timeout={{ .Values.controller.unstageTimeout }}
            - --restage-timeout={{ .Values.controller.restageTimeout }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: metrics
              containerPort: 8080
            - name: health
              containerPort: 8081
            - name: webhook
              containerPort: 9443
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
          volumeMounts:
            - name: webhook-certificate
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
      volumes:
        - name: webhook-certificate
          secret:
            secretName: volumediator-webhook-certificate
