apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}:volumediator-controller
  labels:
    {{- include "volumediator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "pods"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete"]
  - apiGroups: [""]
    resources: ["pods/eviction"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
  - apiGroups: ["volumediator.tarik02.me"]
    resources: ["volumeremediations"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["volumediator.tarik02.me"]
    resources: ["volumeremediations/status", "volumeremediations/finalizers"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}:volumediator-controller
  labels:
    {{- include "volumediator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}:volumediator-controller
subjects:
  - kind: ServiceAccount
    name: volumediator-controller
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}:volumediator-node
  labels:
    {{- include "volumediator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["volumediator.tarik02.me"]
    resources: ["volumeremediations"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: ["volumediator.tarik02.me"]
    resources: ["volumeremediations/status"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}:volumediator-node
  labels:
    {{- include "volumediator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}:volumediator-node
subjects:
  - kind: ServiceAccount
    name: volumediator-node
    namespace: {{ .Release.Namespace }}
