apiVersion: v1
kind: ServiceAccount
metadata:
  name: volumediator-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "volumediator.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: volumediator-node
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "volumediator.labels" . | nindent 4 }}
