apiVersion: v1
kind: Service
metadata:
  name: volumediator-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "volumediator.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: volumediator
    app.kubernetes.io/component: controller
  ports:
    - name: https
      port: 443
      targetPort: webhook
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Release.Namespace }}-volumediator
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/volumediator-webhook
  labels:
    {{- include "volumediator.labels" . | nindent 4 }}
webhooks:
  - name: pods.volumediator.tarik02.me
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore
    timeoutSeconds: 5
    reinvocationPolicy: Never
    clientConfig:
      service:
        name: volumediator-webhook
        namespace: {{ .Release.Namespace }}
        path: /mutate-v1-pod
        port: 443
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: Namespaced
